#!/bin/zsh
PATH="/opt/e17/bin:/opt/e16/bin:/opt/bin:${PATH}"
SCROLLBACK=2048
#FONT='-misc-fixed-bold-r-normal--13-120-75-75-c-80-iso8859-15'
#FONT='-misc-liberation mono-medium-r-normal--15-0-0-0-m-0-iso8859-15'
#FONT='-urw-nimbus mono l-medium-r-normal--15-0-0-0-m-0-iso8859-15'
#FONT='-xos4-terminus-medium-r-normal--18-*-*-*-c-*-iso8859-15'
#FONT='-misc-fixed-medium-r-normal--18-*-*-*-c-*-iso8859-15'
FONT='-*-liberation mono-medium-r-normal--18-*-*-*-*-*-iso8859-15'
# set -x
exec Eterm								\
	-F "${FONT}"							\
	--background-color	'#000000'				\
	--cursor-color		'gold'					\
	--cursor-text-color	'gold3'					\
	--double-buffer							\
	--font-fx		'shadow top_left #203070'		\
	--foreground-color	'gold2'					\
	--itrans							\
	--pointer-color		'gold3'					\
	--resize-gravity						\
	--save-lines		"${SCROLLBACK}"				\
	--scrollbar-type	'next'					\
	--theme			'smoked_glass'				\
	--trans								\
	--visual-bell							\
	$@
exit 1
	--cmod			128 128 128				\
	--cmod-blue		128 128 128				\
	--cmod-green		128 128 128				\
	--cmod-red		128 128 128				\
	--shade			75					\
	--tint			'white'					\
